### ISSUE TITLE
Emulation of Steam Controller prevents sleep on Ayaneo Air Pro

### ISSUE THREAD

**Issue by Alexmjacobs** [SteamFork/bugtracker#2]
On Ayaneo Air Pro 5560u 512GB

As above when steam deck controller emulation is selected the unit will not sleep. Screen turns off but fan is still running.

Pressing the power button then will not wake up the unit.

When "default" controller is selected in decky plumber sleep works perfectly.

As I work around if I need to sleep I go back to "default" controller before pressing the power button and sleep functions great.

Additionally selecting Steam controller also stops the volume rocker from working (You are aware of this I am sure).

Thank you again for your work.

**Comment by fewtarius** [comment]
InputPlumber is still in development, and has a few items like this remaining.  It's not really a bug, you're just experiencing incomplete features.

It's probably a good idea to ask about things like this in Discord where the wider community will see it and be able to help give guidance.

**Comment by Alexmjacobs** [comment]
Got it! Thank you.
