### ISSUE TITLE
Aya Neo Air 5560u no wake on sleep

### ISSUE THREAD

**Issue by Keeseexteewan** [SteamFork/bugtracker#3]
# BUG REPORT

## BEFORE SUBMITTING
1. Make sure SteamFork is fully updated, and re-test if necessary.
2. Ensure that the bug cannot be recreated on a real Steam Deck.

Review the [README](https://github.com/SteamFork/bugtracker) before opening this issue.  Failure to follow the process will result in a closed request and may result in your permission to open bugs being revoked.

## Describe the bug
Aya Neo Air No Wake after consecutive sleep

## To Reproduce
Precise steps to reproduce the behavior:
1. Power on device. 
2. After booting into OS, put device to sleep either via menu or power button. 
3. Wake device via power button
4. Put device to sleep again, same methods as step 2. 
5. Wake device similar to step 3. Device remains at black screen with no video or audio output, only fan spin. 
6. Hold power button to completely shut down device. 
7. Steps 1-6 are repeatable afterwards, exactly 1 wake up/quick resume until device lock up. 

## Expected behavior
Device wakes after sleep, consistently.

## Steps taken to validate on a Steam Deck
Tested on Steam Deck, OS Version 3.5.19, Kernel 6.1.52-valve16-1-neptune-61.
Suspends and wakes as expected.

## Hardware Information

Aya Neo
Air
Ryzen 5 5560u
16GB
512GB SSD
20240928.0902

**Comment by uejji** [comment]
Temporary fix:
Download the two .zst files here to your Air: https://github.com/uejji/steamfork_distribution/releases/tag/20240918-legacy
Then in a terminal on your Air:
```
cd Downloads  # or wherever you placed them
sudo steamos-readonly disable
sudo pacman -U *.zst  # enter y
sudo steamos-readonly enable
```

then reboot

**Comment by Keeseexteewan** [comment]
Downloaded files and followed instructions and successfully downgraded to kernel 6.10.10-5

Tested suspend/wake in game mode as well as in mgba, pcsx2 and steam games at least 5 times each. 

System woke from sleep as expected every time.
